### ISSUE TITLE
看到个道路提取的专利也叫dlinknet

### ISSUE THREAD

**Issue by SonwYang** [zlkanata/DeepGlobe-Road-Extraction-Challenge#30]
https://www.baiten.cn/patent/detail/4e22fa2caab81ed9946867aa7fe32cb7bef5914376be05b9?sc=&fq=&type=&sort=&sortField=&q=dlinknet&rows=10#1/CN201910902885.7/detail/abst

**Comment by zlckanata** [comment]
看起来改进过的 :smirk:
