### ISSUE TITLE
Error when I run train.py

### ISSUE THREAD

**Issue by Ghttt345** [zlkanata/DeepGlobe-Road-Extraction-Challenge#31]
① (when num_workers=4)
raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 12488) exited unexpectedly
② (when num_workers=0)
Process finished with exit code -1073741795 (0xC000001D)

anyone please who can help

**Comment by zlckanata** [comment]
Maybe you can check your python & pytorch version, python 2.7 & pytorch 0.2.0 are preferable for this repo.
