### ISSUE TITLE
数据归一化时的处理（//255 * 3.2 - 1.6）

### ISSUE THREAD

**Issue by Xu-Zirui** [zlkanata/DeepGlobe-Road-Extraction-Challenge#35]
您好，有幸拜读了您的代码和论文，想请问您在归一化时 “ *3.2 - 1.6 “这一步是出于什么考虑呢？

**Comment by zlckanata** [comment]
这个归一化没有太多理论依据，只是一个经验参数，调归一化可以等价于调初始化方差以及学习率等。

实验中，对于没有 BN 的网络（例如此项目中的 Unet），这种归一化方式可以轻微提点；对于有 BN 的网络（例如此项目中的其他网络），是否做归一化以及如何归一化都是不重要的。

**Comment by Xu-Zirui** [comment]
谢谢解答
