### ISSUE TITLE
希望借用codalab账号

### ISSUE THREAD

**Issue by twigsWHy** [zlkanata/DeepGlobe-Road-Extraction-Challenge#38]
我在复现您的代码后，申请了对应的比赛但是一直没有收到批复，无法对模型输出的验证集的mask进行iou精度评估。
是否可以向您借一下codalab的账号以提交结果进行精度评估？
我的邮箱：wanghy08@foxmail.com
谢谢！

**Comment by zlckanata** [comment]
账号不方便共享的，建议您向 deepglobe 组织者发送邮件进行申请

**Comment by twigsWHy** [comment]
好的，谢谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zlckanata/DeepGlobe-Road-Extraction-Challenge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月19日(星期三) 上午9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zlckanata/DeepGlobe-Road-Extraction-Challenge] 希望借用codalab账号 (Issue #38)





 
账号不方便共享的，建议您向 deepglobe 组织者发送邮件进行申请
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
