### ISSUE TITLE
Testing higher resolution data with lower-resolution trained model

### ISSUE THREAD

**Issue by rahul-nt** [zlkanata/DeepGlobe-Road-Extraction-Challenge#5]
Hi
I have trained the d-link model on the training images from DeepGlobe data. Now I'm trying to run the test on the data from Roadtracer images, which are 4096x4096. I changed the resolution in the test.py file. However, it eventually gives a CUDA memory error, despite having 10 GB of GPU memory. Do you have any suggestions to make this work?

**Comment by zlkanata** [comment]
Due to U-shape structure and the shortcuts in the center part, the forward pass in test phase is still somewhat memory consuming. Better crop the images(4096) to small patches(like 2048, maybe with overlap), and then feed to the network one by one.
