### ISSUE TITLE
Could you provide the trained the weight that already trained?

### ISSUE THREAD

**Issue by Jack12xl** [zlkanata/DeepGlobe-Road-Extraction-Challenge#9]
Pretty thanks for your awesome contribution!
But would it be possible for you to provide the weights that were already trained? Since that might save us a lot of training time and help us to evaluate the code?
I once tried to `solver.load('weights/weights')` in test.py but it failed 0.0

**Comment by zlkanata** [comment]
You can find the download link here.
https://github.com/zlkanata/DeepGlobe-Road-Extraction-Challenge#download-trained-d-linknet34

**Comment by Jack12xl** [comment]
Oh!!! Sry I missed that 0.0
